set(COMMON_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../include")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -I ${COMMON_INCLUDE_DIR}")
set(COMMON_FILES ${CMAKE_CURRENT_SOURCE_DIR}/../../src/challenge2.cpp)

